version: 0.2

phases:
  install:
    commands:
      - mkdir logs
      - mkdir files
      - supervisord
      - supervisorctl
      - supervisorctl reread
      - supervisorctl update
      - python -m virtualenv env -p python3.5
      - . env/bin/activate
      - pip install --upgrade pip
      - pip install -q -r deployment/requirements.txt
  build:
    commands:
      - python app/manage.py test