version: 0.2

phases:
  install:
    commands:
      - supervisord
      - supervisorctl
      - supervisorctl reread
      - supervisorctl update
      - python -m virtualenv env -p python3.5
      - . env/bin/activate
      - pip install --upgrade pip
      - pip install -q -r requirements.txt
  pre_build:
    commands:
      - supervisord
      - supervisorctl
      - supervisorctl reread
      - supervisorctl update
  build:
    commands:
      - cd app
      - python manage.py test