# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 17:18
from __future__ import unicode_literals

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DueDate',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('downloaded', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_id', models.TextField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialFile',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.File')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Material')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialTag',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Material')),
            ],
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatternFile',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.File')),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Pattern')),
            ],
        ),
        migrations.CreateModel(
            name='PatternTag',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Pattern')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('complete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMaterial',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Material')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPattern',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Pattern')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('complete', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStatusFile',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.File')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStatusTag',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MakerProfile',
            fields=[
                ('maker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                               related_name='profile', serialize=False, to='bot.Maker')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField(default=None, null=True)),
                ('gender', models.CharField(default=None, max_length=24, null=True)),
                ('timezone', models.IntegerField(default=0)),
                ('locale', models.CharField(max_length=24)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDueDate',
            fields=[
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                                 related_name='project_due_date', serialize=False, to='bot.Project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStatusCompletion',
            fields=[
                ('project_status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                                        related_name='completion', serialize=False,
                                                        to='bot.ProjectStatus')),
                ('percentage', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='projecttag',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Project'),
        ),
        migrations.AddField(
            model_name='projecttag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Tag'),
        ),
        migrations.AddField(
            model_name='projectstatustag',
            name='project_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.ProjectStatus'),
        ),
        migrations.AddField(
            model_name='projectstatustag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Tag'),
        ),
        migrations.AddField(
            model_name='projectstatusfile',
            name='project_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.ProjectStatus'),
        ),
        migrations.AddField(
            model_name='projectstatus',
            name='files',
            field=models.ManyToManyField(related_name='project_statuses', through='bot.ProjectStatusFile',
                                         to='bot.File'),
        ),
        migrations.AddField(
            model_name='projectstatus',
            name='maker',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='project_statuses', to='bot.Maker'),
        ),
        migrations.AddField(
            model_name='projectstatus',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses',
                                    to='bot.Project'),
        ),
        migrations.AddField(
            model_name='projectstatus',
            name='tags',
            field=models.ManyToManyField(related_name='project_statuses', through='bot.ProjectStatusTag', to='bot.Tag'),
        ),
        migrations.AddField(
            model_name='projectpattern',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Project'),
        ),
        migrations.AddField(
            model_name='projectmaterial',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects',
                                    to='bot.Maker'),
        ),
        migrations.AddField(
            model_name='project',
            name='materials',
            field=models.ManyToManyField(related_name='projects', through='bot.ProjectMaterial', to='bot.Material'),
        ),
        migrations.AddField(
            model_name='project',
            name='patterns',
            field=models.ManyToManyField(related_name='projects', through='bot.ProjectPattern', to='bot.Pattern'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(related_name='projects', through='bot.ProjectTag', to='bot.Tag'),
        ),
        migrations.AddField(
            model_name='patterntag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Tag'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='files',
            field=models.ManyToManyField(related_name='patterns', through='bot.PatternFile', to='bot.File'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns',
                                    to='bot.Maker'),
        ),
        migrations.AddField(
            model_name='pattern',
            name='tags',
            field=models.ManyToManyField(related_name='patterns', through='bot.PatternTag', to='bot.Tag'),
        ),
        migrations.AddField(
            model_name='materialtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.Tag'),
        ),
        migrations.AddField(
            model_name='material',
            name='files',
            field=models.ManyToManyField(related_name='materials', through='bot.MaterialFile', to='bot.File'),
        ),
        migrations.AddField(
            model_name='material',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials',
                                    to='bot.Maker'),
        ),
        migrations.AddField(
            model_name='material',
            name='tags',
            field=models.ManyToManyField(related_name='materials', through='bot.MaterialTag', to='bot.Tag'),
        ),
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files',
                                    to='bot.FileType'),
        ),
        migrations.AddField(
            model_name='duedate',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='due_dates',
                                    to='bot.Maker'),
        ),
        migrations.AddField(
            model_name='projectduedate',
            name='due_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_due_dates',
                                    to='bot.DueDate'),
        ),
        migrations.AddField(
            model_name='makerprofile',
            name='profile_picture',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='bot.File'),
        ),
    ]
