# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 02:51
from __future__ import unicode_literals

from django.db import migrations


def forwards_func(apps, schema_editor):
    from bot.lib.conversation import create_conversation, create_conversation_stage

    conversations = dict(
        menu=['menu'],
        create_supplies=['add_context', 'add_image'],
        update_project_status=['add_image', 'how_complete', 'project_selection'],
        create_project=[]
    )
    for name, stages in conversations.items():
        conversation = create_conversation(name=name)
        for stage in stages:
            create_conversation_stage(conversation_name=name, stage_name=stage)


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('bot', '0004_project_finished'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
